#!/usr/bin/env ruby

require "./lib/gnip_downloader"
require "./lib/extraction_runner"
require "./lib/report_publisher"

today_string =  "20131215"
downloader = GnipDownloader.new(skip_download:true, today_string:today_string)
downloader.download_and_unpack
#start_date = Time.now-1
#end_date = Time.now
start_date = DateTime.strptime(today_string, "%Y%m%d")
end_date = DateTime.strptime("20140108", "%Y%m%d")
extractor = ExtractionRunner.new(source_dir_path:downloader.output_dir_path, start_date:start_date, end_date:end_date)
extractor.process
puts extractor.message
publisher = ReportPublisher.new()
publisher.publish_reports(extractor.processed_reports)
puts "\n\n\n\n"

rejects_extractor = ExtractionRunner.new(source_dir_path:downloader.output_dir_path, start_date:start_date, end_date:end_date, invert_filters:true)
rejects_extractor.process
puts rejects_extractor.message
puts publisher.message  # output the message from publishing the main link reports before re-using the publisher for the reject reports
publisher.publish_reports(rejects_extractor.processed_reports)
puts publisher.message
